service: web3-university

layers:
  dependencies:
    path: layer
    description: "Node.js dependencies layer"
    compatibleRuntimes:
      - nodejs20.x

provider:
  name: aws
  runtime: nodejs20.x
  region: ${file(./config/${self:provider.stage}.yml):region, 'us-east-2'}
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${self:provider.stage}
    DYNAMODB_USERS_TABLE: ${self:service}-${self:provider.stage}-users
    DYNAMODB_COURSES_TABLE: ${self:service}-${self:provider.stage}-courses
    S3_BUCKET_NAME: ${self:service}-${self:provider.stage}
    LOG_LEVEL: ${file(./config/${self:provider.stage}.yml):logLevel, 'INFO'}
    JWT_SECRET: ${env:JWT_SECRET, 'fallback_secret_key'}
  layers:
    - {Ref: DependenciesLambdaLayer}
  memorySize: ${file(./config/${self:provider.stage}.yml):memorySize, 1024}
  timeout: ${file(./config/${self:provider.stage}.yml):timeout, 29}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:ListTables
          Resource: "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/*"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
          Resource:
            - !GetAtt UsersTable.Arn
            - !Join ["", [!GetAtt UsersTable.Arn, "/index/*"]]
            - !GetAtt CoursesTable.Arn
            - !Join ["", [!GetAtt CoursesTable.Arn, "/index/*"]]
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource: 
            - !Join ["", ["arn:aws:s3:::", "${self:service}-${self:provider.stage}", "/*"]]

functions:
  api:
    handler: dist/src/lambda.handler
    layers:
      - {Ref: DependenciesLambdaLayer}
    events:
      - http:
          path: /{proxy+}
          method: any
          cors:
            origin: 'http://localhost:3000,https://senmu.site,https://biglove.top'
            headers:
              - Content-Type
              - Authorization
              - X-Requested-With
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - Origin
              - Accept
            allowCredentials: true
            maxAge: 600

resources:
  Resources:
    # 用户表
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_USERS_TABLE}
        BillingMode: PAY_PER_REQUEST # 按需计费模式
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: walletAddress
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: walletAddressIndex
            KeySchema:
              - AttributeName: walletAddress
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    
    # 课程表 - 极简表结构
    CoursesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_COURSES_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: web2CourseId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: web2CourseIdIndex
            KeySchema:
              - AttributeName: web2CourseId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    
    # S3 存储桶
    ContentBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              AllowedOrigins:
                - "*"
              MaxAge: 3000

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: ./.env.${opt:env, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: false
    packager: "yarn"
    packagerOptions:
      scripts:
        - rm -rf node_modules/aws-sdk
